### ISSUE TITLE
Questions regarding DIN 91379:2022-08

### ISSUE THREAD

**Issue by flxbe** [String-Latin/DIN-91379-Characters-and-Sequences#1]
Hi

First of all thanks for uploading the files! This project has been really helpful.

I am currently trying to get a hold of the details of DIN 91379, however I want to avoid actually buying the document, as I only need the information for a private project. I was therefore hoping you could help me answer some of my open questions or point me into the right direction.

1. DIN 91379 deprecates several characters and specifies their replacement (e.g. `Ŀ` -> `L·`). Are strings containing deprecated characters considered valid for the new standard? Or MUST valid implementations of the data types convert the deprecated characters to their new form?
2. DIN 91369 introduces new characters, two of which are not deprecated (`′` (U+2032) and `″` (U+2033)). This would make some the data types in DIN 91379 incompatible with the same data types from DIN SPEC 91379. Are there any rules about how to downgrade to the former version of the standard? Or is DIN 91379 simply a non-compatible new version of the standard?

Many thanks!

**Comment by vk-github18** [comment]
Hi @flxbe, 
my current understanding is as follows:
1. The currently deprecated characters and sequences belong to the normative group "bll", they are considered valid and have to be supported by a compliant system. They don't have to be automatically converted to their replacement. However, they were only introduced to be able to process old (and partly handwritten) register entries and should be avoided. An application consuming data must be able to handle the deprecated characters and sequences, an application sending data should not send deprecated characters and sequences.
2. PRIME and DOUBLE PRIME belong to the extended group "enl", they should be supported for names of legal entities and products, but their support is not required for conformance to the norm. DIN 91379 supports a few more characters and sequences than DIN SPEC 91379. A system compliant to DIN 91379 is also compliant to DIN SPEC 91379, but not vice versa.
3. I assume that the DIN standard can be read in your nearest university library.

**Comment by flxbe** [comment]
Thanks for the clarifications. Also looking up the standard in a university library is a very good idea, I haven't thought about that possibility yet.

Just FYI, I uploaded the project for which I needed the DIN norm to github. Should you come around to have a look at it I would of course appreciate any feedback: https://github.com/flxbe/Din91379-csharp
